# -*- coding: utf-8 -*-
"""codePark - Repeticao Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQxGm6bNaqYS0YdRucTsGs0I5IqUMUgM

Precisamos imprimir um número para cada andar de um hotel de 20 andares. Porém, o dono do hotel é supersticioso e optou por não ter um 13ro andar.

Escreva um código que imprima todos os números exceto o número 13.
Escreva mais dois códigos que resolvam o mesmo problema, mas dessa vez usando os outros dois tipos de laços de repetição aprendidos.

Como desafio, imprima eles em ordem decrescente (20, 19, 18...)
"""

# EXEMPLO-01
ultimoAndar = 20
primeiroAndar = 0

for andarAtual in range(primeiroAndar, ultimoAndar+1):
  if ultimoAndar-andarAtual != 13:
    print('Andar: ', ultimoAndar-andarAtual)
  else:
    continue # Continua a execucao para o proxima iteracao
print('Acabaram os andares do predio.')

# EXEMPLO-02
ultimoAndar = 20
primeiroAndar = 0

andarAtual = 0

while (andarAtual != ultimoAndar+1):
  print('Andar: ', ultimoAndar - (primeiroAndar + andarAtual))
  andarAtual = andarAtual + 1

print("Finalizou")

for andar in range(1,21):
    if (andar != 13):
        print("Andar ", andar)